# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/path_expander/all/path_expander.rbi
#
# path_expander-1.1.0

class PathExpander
  def args; end
  def args=(arg0); end
  def expand_dirs_to_files(*dirs); end
  def filter_files(files, ignore); end
  def glob; end
  def glob=(arg0); end
  def initialize(args, glob, path = nil); end
  def path; end
  def path=(arg0); end
  def process; end
  def process_args; end
  def process_file(path); end
  def process_flags(flags); end
end
