name: Test
on:
  - push
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.5.8
          - 2.6.6
          - 2.7.2
          - 3.0.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: COVERAGE=1 bundle exec rake test:unit
      - uses: codecov/codecov-action@v1
        with:
          files: ./coverage/codecov-result.json
  documentation:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
      - run: |
          bin/yard
          git fetch origin gh-pages
          git checkout gh-pages
          git clean --force --exclude=doc
          git ls-files | xargs git rm
          mv docs/* .
          git add .
          git commit -m "Update documentation"
          git push
