name: Test
on:
  - push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
      - run: COVERAGE=1 bundle exec rake test:unit
      - uses: codecov/codecov-action@v1
        with:
          files: ./target/coverage/codecov.json
